name: Merge Develop Actions

on:
  pull_request:
    branches: ['develop']

jobs:
  lint-be:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint backend
        run: |
          npm install
          npm run lint

  test-be:
    runs-on: ubuntu-latest
    needs: [lint-be]

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test frontend
        run: |
          npm install
          npm run test

  deploy-develop:
    runs-on: ubuntu-latest
    needs: ['test-be']

    steps:
      - name: Trigger Webhook
        run: |
          curl -X ${{secrets.DEVELOP_DEPLOY_HOOK}}
