name: Deploy to Develop

on:
  push:
    branches: [develop]

jobs:
  deploy-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Webhook
        run: |
          curl -X ${{secrets.DEVELOP_DEPLOY_HOOK}}
